; PlatformIO Project Configuration
; CrowPanel 7.0" HMI ESP32-S3 Display (800x480 RGB TFT LCD Touch Screen)
; MCU: ESP32-S3 (4MB Flash, 8MB OPI PSRAM)
; Display: 800x480 RGB565 (EK9716 + EK73002)
; Touch: GT911 Capacitive (I2C)

[env:crowpanel-7]
platform = espressif32@53.3.10
board = esp32-s3-devkitc-1
framework = arduino

; --- Flash & PSRAM Configuration ---
; CrowPanel 7" has 4MB Flash (DIO) + 8MB OPI PSRAM
board_build.arduino.memory_type = dio_opi
board_build.flash_mode = dio
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
board_build.partitions = huge_app.csv

; --- Upload & Monitor ---
monitor_speed = 115200
upload_speed = 921600

; --- Build Flags ---
build_flags = 
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DLV_CONF_INCLUDE_SIMPLE
    -I include
    -I C:/Users/Adi/.platformio/packages/framework-arduinoespressif32/libraries/Network/src
lib_ldf_mode = deep+
lib_extra_dirs = 
    C:/Users/Adi/.platformio/packages/framework-arduinoespressif32/libraries

; --- Libraries ---
lib_deps = 
    moononournation/GFX Library for Arduino@^1.4.9
    tamctec/TAMC_GT911@^1.0.2
    lvgl/lvgl@^8.4.0
